"""initial migration
Revision ID: 38312a1a305e
Revises: 124e1c4c979f
Create Date: 2024-05-05 15:55:24.028259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38312a1a305e'
down_revision: Union[str, None] = '124e1c4c979f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_created_by_fkey', 'events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('events_created_by_fkey', 'events', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###